@token= eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0YXouaGFyZGluZy5lZHUiLCJzdWIiOiJmdmlkZXMiLCJhdWQiOiJ0ZXN0Iiwicm9sZXMiOltdLCJpYXQiOjE2Nzk5NzY3NTAsImV4cCI6MTY4MjU2ODc1MH0.7nleaLLJOe0tXt155gV1OPglirMG7jSXRlrAATy7frA8q_o-F361aGedKaPw2wVeOJ4uFmbP5i_fCOZd2IFvu0q-mNPj42svGsGtO1MlPe8Xq8j-0qYDVTST6N3K5HSgyVtCp1X0YJmDIgdjjAAfMduw5tLG1z32gPr5qK0A3DUcwjrcv5_oi-eSD9vOExNhEpSIpUsxdqq3EoSTRLfgpKrwAFETWI9RlOfEcXl3emgMxACyNSVT38oaNi3cS85is_bOvoSIu_2LfWHfhAHm6ER6DV05nuL8Sfzj1ZVot4lAl6rkTI0OQnUoIFPfgrqhUzcSC0mYIVM_aXE4XeI57A


GET http://localhost:8000/api/questions
###

POST http://localhost:8000/api/questions
Content-Type: application/json
{
    "summary": "first try with REST request",
    "contents": "lorem ipsum",
    "author": "itzi"
}
###
GET http://localhost:8000/api/questions/6420e2e8e5dd289debfb187d

GET http://localhost:8000/api/questions/6421e9af9b26713b307c2a63
###
PUT http://localhost:8000/api/questions/6420d7dfa3dbedb2f883ab6c

PUT http://localhost:8000/api/questions/64213ee1dc6ba0f5a0e47c67
Content-Type: application/json

{
    "summary": "Second try",
    "contents": "lorem ipsum",
    "author": "MartinTercero"
}
###
POST http://localhost:8000/api/questions/6420f287acb2fea6e2835f27/answers

###
GET http://localhost:8000/api/questions/6422026d0d6fb94ceb167536/answers
###

POST http://localhost:8000/api/questions/6422026d0d6fb94ceb167536/answers
Content-Type: application/json

{
    "contents": "yessir, you will  get there",
    "author": "evaught"
}
###

GET http://localhost:8000/api/answers/642202830d6fb94ceb167539
###

PUT http://localhost:8000/api/answers/6421fdcbf06ebb924a2fa0e1
Content-Type: application/json

{
    "contents": "I changed my mind...",
    "author": "JavierAlfaro2"
}
###

DELETE http://localhost:8000/api/questions
###
GET http://localhost:8000/api/hello
UPDATE http://localhost:8000/api/questions

###
GET http://localhost:8000/api/likes/6420e2f7e5dd289debfb187f

###
POST http://localhost:8000/api/likes/6420e2f7e5dd289debfb187f/mtercero1
Authorization: Bearer {{token}}

###