@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0YXouaGFyZGluZy5lZHUiLCJzdWIiOiJtdGVyY2VybzEiLCJhdWQiOiJ0ZXN0Iiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNjgwMDUzMTE0LCJleHAiOjE2ODAwNTY3MTR9.Ykfuq-jhU-jxVjjkd095XDRpHl1dBwyL2JFR3setPofF_p4MrT5nEy-lWOxMaNC_CG-GChLx2BDzA97wqOfydzwpjr4FA5JR4Ge0VcxYpFWlgaZPeRXxiaNBl-j_EUVsNYcJIvYMlSCjjgq2al6xijPuX2FjPbtvPOsFx-LzZ2RZgPjuE9Qri9qrWn0RMeeP-78A_KSYAuCy10laz7SKI094X_L1Y9Iq1UE0ykNIwG_3F7MNCLX4mGfxuoihN9yh5WpxNI9Ux5xr66hPWmBLqC6tikMUiCufrpQM74DW7V4H5G_OK_A9BvPU2Nll3_tGdV13WL3rOanMzM2japLanw
GET http://localhost:8000/api/questions
###

POST http://localhost:8000/api/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "summary": "7 try with REST request",
    "contents": "lorem ipsum",
    "author": "mtercero1"
}
###

GET http://localhost:8000/api/questions/64239bfbfc751f685f7709b8
###

PUT http://localhost:8000/api/questions/642396e3c248f4e5feef8aeb
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "summary": "UPDATEEEEE",
    "contents": "lorem ipsum",
    "author": "MartinTercero"
}
###

GET http://localhost:8000/api/questions/6421e76e799340b45507bb8a/answers
###

POST http://localhost:8000/api/questions/6421e76e799340b45507bb8a/answers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "contents": "yessir, you will  get there",
    "author": "evaught"
}
###

GET http://localhost:8000/api/answers/642398746b8863bd8c18a1e9
###

PUT http://localhost:8000/api/answers/642398746b8863bd8c18a1e9
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "contents": "I changed my mind...",
    "author": "JavierAlfaro2"
}
###

DELETE http://localhost:8000/api/questions
###

GET http://localhost:8000/api/questionsSSS
###

GET http://localhost:8000/api/likes/6420e2f7e5dd289debfb187f
###

GET http://localhost:8000/api/likes/6420e2f7e5dd289debfb187f/mtercero1
Authorization: Bearer {{token}}
###

POST http://localhost:8000/api/likes/6420e2f7e5dd289debfb187f/mtercero1
Authorization: Bearer {{token}}
###

DELETE http://localhost:8000/api/likes/6420e2f7e5dd289debfb187f/mtercero1
Authorization: Bearer {{token}}
###